; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware
lib_dirs = lib
extra_configs = platformio_local.ini

[env]
build_flags = 
	-D MAX_NUM_SLAVE=20
	-D BOARD_HAS_PSRAM            ; Enable PSRAM support
	;----------睇Log專用----------
	-D DEBUG_ENABLED=1 ;0＝不需要Log 1=需要
	-D LOG_TIMESTAMPS=1 ;0＝不需要log時間 1=需要

[env:master_base]
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = 
	+<master/src/*.cpp>
	+<shared/src/*.cpp>
	+<shared/src/storymode/*.cpp>
	+<shared/src/patterns/*.cpp>
	+<shared/src/lib/*.cpp>
build_flags = 
	${env.build_flags}
	-I master/include
	-I shared/include
	-D IS_MASTER=1
	-D SLAVE_I2C_ADDR=0x10  ; 不用改這裡！
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-DPIO_FRAMEWORK_ARDUINO_SPIFFS_ENABLE
	-DARDUINO_USB_PSRAM_DIO        ; Enable PSRAM in DIO mode
board_build.filesystem = spiffs 
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = partitions_ota.csv
lib_deps = 
	fastled/FastLED@3.9.6
	madhephaestus/ESP32Encoder
	https://github.com/tzapu/WiFiManager.git
	mathertel/OneButton
	adafruit/Adafruit BusIO@^1.16.2
	bakercp/CRC32@^2.0.0  ; For OTA checksums
	; adafruit/Adafruit PWM Servo Driver Library@^3.0.2
monitor_speed = 115200
upload_speed = 115200

[env:slave1_base] 
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = 
	+<slave/src/*.cpp>
	+<shared/src/*.cpp>
	+<shared/src/storymode/*.cpp>
	+<shared/src/patterns/*.cpp>
	+<shared/src/lib/*.cpp>
build_flags = 
	${env.build_flags}
	-I slave/include
	-I shared/include

	;----------SLAVE設定----------
	-D IS_SLAVE=1
	-D SLAVE_I2C_ADDR=0x10
	-D SLAVE_ID=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = partitions_ota.csv
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit BusIO@^1.16.2
	bakercp/CRC32@^2.0.0
monitor_speed = 115200
upload_speed = 115200

[env:slave2_base] 
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = 
	+<slave/src/*.cpp>
	+<shared/src/*.cpp>
	+<shared/src/storymode/*.cpp>
	+<shared/src/patterns/*.cpp>
	+<shared/src/lib/*.cpp>
build_flags = 
	${env.build_flags}
	-I slave/include
	-I shared/include

	;----------SLAVE設定----------
	-D IS_SLAVE=1
	-D SLAVE_ID=2
	-D SLAVE_I2C_ADDR=0x11
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = partitions_ota.csv
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit BusIO@^1.16.2
	bakercp/CRC32@^2.0.0
monitor_speed = 115200
upload_speed = 115200

[env:slave3_base] 
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = 
	+<slave/src/*.cpp>
	+<shared/src/*.cpp>
	+<shared/src/storymode/*.cpp>
	+<shared/src/patterns/*.cpp>
	+<shared/src/lib/*.cpp>
build_flags = 
	${env.build_flags}
	-I slave/include
	-I shared/include

	;----------SLAVE設定----------
	-D IS_SLAVE=1
	-D SLAVE_ID=3
	-D SLAVE_I2C_ADDR=0x12
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = partitions_ota.csv
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit BusIO@^1.16.2
	bakercp/CRC32@^2.0.0
monitor_speed = 115200
upload_speed = 115200

[env:slave4_base] 
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = 
	+<slave/src/*.cpp>
	+<shared/src/*.cpp>
	+<shared/src/storymode/*.cpp>
	+<shared/src/patterns/*.cpp>
	+<shared/src/lib/*.cpp>
build_flags = 
	${env.build_flags}
	-I slave/include
	-I shared/include

	;----------SLAVE設定----------
	-D IS_SLAVE=1
	-D SLAVE_ID=4
	-D SLAVE_I2C_ADDR=0x13
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = partitions_ota.csv
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit BusIO@^1.16.2
	bakercp/CRC32@^2.0.0
monitor_speed = 115200
upload_speed = 115200

[env:slave5_base] 
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = 
	+<slave/src/*.cpp>
	+<shared/src/*.cpp>
	+<shared/src/storymode/*.cpp>
	+<shared/src/patterns/*.cpp>
	+<shared/src/lib/*.cpp>
build_flags = 
	${env.build_flags}
	-I slave/include
	-I shared/include

	;----------SLAVE設定----------
	-D IS_SLAVE=1
	-D SLAVE_ID=5
	-D SLAVE_I2C_ADDR=0x14
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = partitions_ota.csv
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit BusIO@^1.16.2
	bakercp/CRC32@^2.0.0
monitor_speed = 115200
upload_speed = 115200

[env:slave6_base] 
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = 
	+<slave/src/*.cpp>
	+<shared/src/*.cpp>
	+<shared/src/storymode/*.cpp>
	+<shared/src/patterns/*.cpp>
	+<shared/src/lib/*.cpp>
build_flags = 
	${env.build_flags}
	-I slave/include
	-I shared/include

	;----------SLAVE設定----------
	-D IS_SLAVE=1
	-D SLAVE_ID=6
	-D SLAVE_I2C_ADDR=0x15
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = partitions_ota.csv
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit BusIO@^1.16.2
	bakercp/CRC32@^2.0.0
monitor_speed = 115200
upload_speed = 115200

[env:slave7_base] 
platform = espressif32
board = lolin_s3_mini
framework = arduino
build_src_filter = 
	+<slave/src/*.cpp>
	+<shared/src/*.cpp>
	+<shared/src/storymode/*.cpp>
	+<shared/src/patterns/*.cpp>
	+<shared/src/lib/*.cpp>
build_flags = 
	${env.build_flags}
	-I slave/include
	-I shared/include

	;----------SLAVE設定----------
	-D IS_SLAVE=1
	-D SLAVE_ID=7
	-D SLAVE_I2C_ADDR=0x16
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio
board_build.flash_freq = 80m
board_build.partitions = partitions_ota.csv
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit BusIO@^1.16.2
	bakercp/CRC32@^2.0.0
monitor_speed = 115200
upload_speed = 115200