; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32dev]
platform = espressif32
board = lolin_s3_mini
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_speed = 115200
build_flags = 
	-D MAX_NUM_PWM=25
	-D ACTUAL_NUM_PWM=3
	-D PWM_ADDRESS_1=0x42
	-D PWM_ADDRESS_2=0x43
	-D PWM_ADDRESS_3=0x44
	-D PWM_ADDRESS_4=0x59
	-D PWM_ADDRESS_5=0x44
	-D PWM_ADDRESS_6=0x45
	-D PWM_ADDRESS_7=0x54
	-D PWM_ADDRESS_8=0x47
	-D PWM_ADDRESS_9=0x48
	-D PWM_ADDRESS_10=0x49
	-D PWM_ADDRESS_11=0x4A
	-D PWM_ADDRESS_12=0x4B
	-D PWM_ADDRESS_13=0x4C
	-D PWM_ADDRESS_14=0x4D
	-D PWM_ADDRESS_15=0x4E
	-D PWM_ADDRESS_16=0x4F
	-D PWM_ADDRESS_17=0x50
	-D PWM_ADDRESS_18=0x51
	-D PWM_ADDRESS_19=0x52
	-D PWM_ADDRESS_20=0x53
	-D PWM_ADDRESS_21=0x54
	-D PWM_ADDRESS_22=0x55
	-D PWM_ADDRESS_23=0x56
	-D PWM_ADDRESS_24=0x57
	-D PWM_ADDRESS_25=0x58
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
	;arduino-libraries/ArduinoFFT@^1.6.0
monitor_port = /dev/cu.usbmodem11201