; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32dev]
platform = espressif32
board = lolin_s3_mini
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_speed = 115200
build_flags = 
	-D MAX_NUM_PWM=5
	-D ACTUAL_NUM_PWM=1
	-D PWM_ADDRESS_1=0x40 ;index 0
	-D PWM_ADDRESS_2=0x43 ;index 1
	-D PWM_ADDRESS_3=0x44 ;index 2
	-D PWM_ADDRESS_4=0x59
	-D PWM_ADDRESS_5=0x44
lib_deps = 
	fastled/FastLED@3.9.6
	adafruit/Adafruit BusIO@^1.16.2
	;arduino-libraries/ArduinoFFT@^1.6.0
monitor_port = /dev/cu.usbmodem11201