; This file is ignored by git to maintain local settings
; Each developer should configure their own port settings here

[env:master]
extends = env:master_base
build_flags = 
    ${env:master_base.build_flags}
	-D WIFI_NAME=\"green_pepper_master\"
    -D ACTUAL_SLAVE_NUM=2
    -D ENABLE_VIDEO_UART=0 ;0＝不需要UART螢幕播片 1=需要UART螢幕播片
    ;----------storymode 運行時長----------
    -D STORYMODE_0_TOTAL_SECONDS=47
    -D STORYMODE_1_TOTAL_SECONDS=176
    -D STORYMODE_2_TOTAL_SECONDS=158
    -D STORYMODE_3_TOTAL_SECONDS=158
    ;----------storymode 閒置時長----------
    -D STORYMODE_0_IDLE=20000UL ; storyMode_0 是20秒
    -D STORYMODE_1_IDLE=30000UL ; storyMode_1 是30秒
    -D STORYMODE_2_IDLE=25000UL ; storyMode_2 是25秒
    -D STORYMODE_99_IDLE=25000UL ; storyMode_99 是25秒
    -D FULL_CYCLE_STORYMODE_IDLE=180000UL ; FULL_CYCLE_STORYMODE 是180秒
    ;-------------------------------------
upload_port = /dev/cu.usbmodem21401
monitor_port = /dev/cu.usbmodem21401

[env:slave1]
extends = env:slave1_base
build_flags = 
    ${env:slave1_base.build_flags}
    ;----------彩色LED燈珠數目----------
    -D NUM_LEDS_RGB0=200
    -D NUM_LEDS_RGB1=100
    -D NUM_LEDS_RGB2=50
    -D NUM_LEDS_RGB3=10
    -D NUM_LEDS_RGB4=10
    ;----------PWM相關設定----------
    -D MAX_NUM_PWM=25
    -D ACTUAL_NUM_PWM=7
    -D PWM_ADDRESS_1=0x40
    -D PWM_ADDRESS_2=0x4A
    -D PWM_ADDRESS_3=0x42
    -D PWM_ADDRESS_4=0x43
    -D PWM_ADDRESS_5=0x44
    -D PWM_ADDRESS_6=0x61
    -D PWM_ADDRESS_7=0x6B
    ;如需要可繼續自行添加，上限是PWM_ADDRESS_25
upload_port = /dev/cu.usbmodem21301
monitor_port = /dev/cu.usbmodem21301

[env:slave2]
extends = env:slave2_base
build_flags = 
    ${env:slave2_base.build_flags}
    ;----------彩色LED燈珠數目----------
    -D NUM_LEDS_RGB0=200
    -D NUM_LEDS_RGB1=100
    -D NUM_LEDS_RGB2=50
    -D NUM_LEDS_RGB3=10
    -D NUM_LEDS_RGB4=10

    ;----------PWM相關設定----------
    -D MAX_NUM_PWM=25
    -D ACTUAL_NUM_PWM=7
    -D PWM_ADDRESS_1=0x40
    -D PWM_ADDRESS_2=0x4A
    -D PWM_ADDRESS_3=0x42
    -D PWM_ADDRESS_4=0x43
    -D PWM_ADDRESS_5=0x44
    -D PWM_ADDRESS_6=0x61
    -D PWM_ADDRESS_7=0x6B
    ;如需要可繼續自行添加，上限是PWM_ADDRESS_25
upload_port = /dev/cu.usbmodem21301
monitor_port = /dev/cu.usbmodem21301

[env:slave3]
extends = env:slave3_base
build_flags = 
    ${env:slave3_base.build_flags}
    ;----------彩色LED燈珠數目----------
    -D NUM_LEDS_RGB0=200
    -D NUM_LEDS_RGB1=100
    -D NUM_LEDS_RGB2=50
    -D NUM_LEDS_RGB3=10
    -D NUM_LEDS_RGB4=10
    ;----------PWM相關設定----------
    -D MAX_NUM_PWM=25
    -D ACTUAL_NUM_PWM=7
    -D PWM_ADDRESS_1=0x40
    -D PWM_ADDRESS_2=0x4A
    -D PWM_ADDRESS_3=0x42
    -D PWM_ADDRESS_4=0x43
    -D PWM_ADDRESS_5=0x44
    -D PWM_ADDRESS_6=0x61
    -D PWM_ADDRESS_7=0x6B
    ;如需要可繼續自行添加，上限是PWM_ADDRESS_25
upload_port = /dev/cu.usbmodem21401
monitor_port = /dev/cu.usbmodem21401

[env:slave4]
extends = env:slave4_base
build_flags = 
    ${env:slave4_base.build_flags}
    ;----------彩色LED燈珠數目----------
    -D NUM_LEDS_RGB0=200
    -D NUM_LEDS_RGB1=100
    -D NUM_LEDS_RGB2=50
    -D NUM_LEDS_RGB3=10
    -D NUM_LEDS_RGB4=10
    ;----------PWM相關設定----------
    -D MAX_NUM_PWM=25
    -D ACTUAL_NUM_PWM=7
    -D PWM_ADDRESS_1=0x40
    -D PWM_ADDRESS_2=0x4A
    -D PWM_ADDRESS_3=0x42
    -D PWM_ADDRESS_4=0x43
    -D PWM_ADDRESS_5=0x44
    -D PWM_ADDRESS_6=0x61
    -D PWM_ADDRESS_7=0x6B
    ;如需要可繼續自行添加，上限是PWM_ADDRESS_25
upload_port = /dev/cu.usbmodem21501
monitor_port = /dev/cu.usbmodem21501

[env:slave5]
extends = env:slave5_base
build_flags = 
    ${env:slave5_base.build_flags}
    ;----------彩色LED燈珠數目----------
    -D NUM_LEDS_RGB0=200
    -D NUM_LEDS_RGB1=100
    -D NUM_LEDS_RGB2=50
    -D NUM_LEDS_RGB3=10
    -D NUM_LEDS_RGB4=10
    ;----------PWM相關設定----------
    -D MAX_NUM_PWM=25
    -D ACTUAL_NUM_PWM=7
    -D PWM_ADDRESS_1=0x40
    -D PWM_ADDRESS_2=0x4A
    -D PWM_ADDRESS_3=0x42
    -D PWM_ADDRESS_4=0x43
    -D PWM_ADDRESS_5=0x44
    -D PWM_ADDRESS_6=0x61
    -D PWM_ADDRESS_7=0x6B
    ;如需要可繼續自行添加，上限是PWM_ADDRESS_25
upload_port = /dev/cu.usbmodem21601
monitor_port = /dev/cu.usbmodem21601

[env:slave6]
extends = env:slave6_base
build_flags = 
    ${env:slave6_base.build_flags}
    ;----------彩色LED燈珠數目----------
    -D NUM_LEDS_RGB0=200
    -D NUM_LEDS_RGB1=100
    -D NUM_LEDS_RGB2=50
    -D NUM_LEDS_RGB3=10
    -D NUM_LEDS_RGB4=10
    ;----------PWM相關設定----------
    -D MAX_NUM_PWM=25
    -D ACTUAL_NUM_PWM=7
    -D PWM_ADDRESS_1=0x40
    -D PWM_ADDRESS_2=0x4A
    -D PWM_ADDRESS_3=0x42
    -D PWM_ADDRESS_4=0x43
    -D PWM_ADDRESS_5=0x44
    -D PWM_ADDRESS_6=0x61
    -D PWM_ADDRESS_7=0x6B
    ;如需要可繼續自行添加，上限是PWM_ADDRESS_25
upload_port = /dev/cu.usbmodem21701
monitor_port = /dev/cu.usbmodem21701

[env:slave7]
extends = env:slave7_base
build_flags = 
    ${env:slave7_base.build_flags}
    ;----------彩色LED燈珠數目----------
    -D NUM_LEDS_RGB0=200
    -D NUM_LEDS_RGB1=100
    -D NUM_LEDS_RGB2=50
    -D NUM_LEDS_RGB3=10
    -D NUM_LEDS_RGB4=10
    ;----------PWM相關設定----------
    -D MAX_NUM_PWM=25
    -D ACTUAL_NUM_PWM=7
    -D PWM_ADDRESS_1=0x40
    -D PWM_ADDRESS_2=0x4A
    -D PWM_ADDRESS_3=0x42
    -D PWM_ADDRESS_4=0x43
    -D PWM_ADDRESS_5=0x44
    -D PWM_ADDRESS_6=0x61
    -D PWM_ADDRESS_7=0x6B
    ;如需要可繼續自行添加，上限是PWM_ADDRESS_25
upload_port = /dev/cu.usbmodem21801
monitor_port = /dev/cu.usbmodem21801